
const dayFacts = {
  1: "The Wright brothers' first flight lasted only 1 day - December 17, 1903",
  2: "It took just 2 days for Instagram to gain 1 million downloads when it launched on iOS",
  3: "The first human spaceflight by Yuri Gagarin lasted 3 days in 1961",
  4: "The first non-stop transatlantic flight took 4 days in 1919",
  5: "Mozart composed his Symphony No. 41 in just 5 days",
  6: "The first text message was developed and sent in 6 days in 1992",
  7: "Alexander Graham Bell's first telephone was built in 7 days",
  8: "The first Polaroid camera was conceived and sketched in 8 days",
  9: "The first successful heart transplant patient survived 9 days in 1967",
  10: "The first transcontinental railroad telegram took 10 days in 1861",
  12: "The first Around the World Hot Air Balloon flight took 12 days in 1978",
  14: "The first color television was assembled in 14 days",
  15: "Leonardo da Vinci sketched the Mona Lisa's basic outline in 15 days",
  20: "The first message to cross the Atlantic cable took 20 days in 1858",
  25: "The first successful submarine voyage lasted 25 days",
  30: "Vincent van Gogh painted 'Starry Night' in about 30 days",
  35: "The first electric light bulb prototype was developed in 35 days",
  40: "The first microprocessor was designed in 40 days",
  45: "The first public railway line was built in 45 days in 1825",
  50: "The first successful polio vaccine was developed in 50 days",
  60: "The Eiffel Tower's main structural work was completed in 60 days",
  75: "The first successful oil well was drilled in 75 days",
  90: "Jules Verne wrote 'Around the World in 80 Days' in 90 days",
  100: "The first automobile assembly line reduced production time to 100 days",
  120: "The first successful radio transmission across the Atlantic took 120 days",
  150: "The first telegraph line across America was completed in 150 days",
  180: "The Great Wall of China's first phase took 180 days",
  200: "The first submarine telegraph cable was laid in 200 days",
  225: "The first commercial computer was assembled in 225 days",
  250: "The Golden Gate Bridge's cables were spun in 250 days",
  275: "The first successful steam engine was built in 275 days",
  300: "The Empire State Building was built in just 300 days",
  325: "The first successful passenger elevator was installed in 325 days",
  350: "The Panama Canal's final phase was completed in 350 days",
  365: "The Great Pyramid of Giza took approximately 365 days for basic structure",
  366: "The first artificial satellite orbited Earth for 366 days"
};
